import { Dimensions } from 'react-native';
const { width, height } = Dimensions.get('window');

const Constants = {
  BASE_API_URL: 'http://www.openhousemarketingsystem.com/application/v2',
  accounturl: 'http://www.openhousemarketingsystem.com/application/',
  shareurl: 'http://www.openhousemarketingsystem.com/',
  user_mail: '',
  user_password: '',
  first_name: '',
  last_name: '',
  agent_title: '',
  email_adress: '',
  cell_number: '',
  broker_name: '',
  MlsData: [],
  searchFlag: 0,
  loadLMSflag: 0,
  updateFlag: 0,
  resetflag: 0,
  eventflag: 0,
  AttendeData: [],
  BrokerData: [],
  eventData: [],
  EventDatas: [],
  propertyData: [],
  uploadPhotoFlag: 0,
  bestsellingfeatures: [],
  postbrokerFlag: 0,
  postpublicbrokerFlag: 0,
  checkArray: [],
  backScreen:'',
  questionScreens: [
    'question1Screen',
    'question2Screen',
    'question3Screen',
    'question4Screen',
    'question5Screen',
    'question6Screen',
    'question7Screen',
    'question8Screen',
    'question9Screen',
    'question10Screen',
    'question11Screen',
    'question12Screen',
  ],
  attendeefirstname: '',
  attendeelastname: '',
  attendeeemail: '',
  attendeetelephone: '',

  attendeepropertylistedyesorno: '0',
  attendeeownorrent: '',
  attendeeneedtosellyesorno: '0',
  attendeereceivecma: '0',
  attendeeprospectmatch: '0',

  attendeeaddress: '',
  attendeecity: '',
  attendeestate: '',
  attendeezipcode: '',

  attendeehowsoonlookingtobuyorrent: '',
  attendeehearaboutlisting: '',
  attendeehowhearaboutlistinganswer: '',
  attendeeareyouprequalified: '',
  attendeeprequalifiedbankname: '',
  attendeehowgoodisyourcredit: '',
  attendeehaverealestateattorney: '0',
  attendeefollowupvia: '',
  postflag: 0,
  disclosureArray: [],
  createNewAccount: [],

  create_userfirstname: '',
  create_userlastname: '',
  create_useremailaddress: '',
  create_userephoneNumber: '',
  create_userpassword: '',
  mortgage_flag: 0,
  device_Pad: false,
  officename:'',
  logo_url:'',

  temp1:'',
  temp2: '',
  temp3: '',
  checkPermission:false,

  mlsSelectedItem:null,
  mlsOrganize:'',
  createeventflag: 0,
};

export default Constants;
